{% set name = "Mathics-Scanner" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mathics_scanner-{{ version }}.tar.gz
  sha256: a98a5ee11815bf94edf8a6f665e788915c09b9cd4fd96ed4fc26583973dc6fb1

build:
  entry_points:
    - mathics3-generate-json-table = mathics_scanner.generate.build_tables:main
    - mathics3-generate-operator-json-table = mathics_scanner.generate.build_operator_tables:main
    - mathics3-tokens = mathics_scanner.mathics3_tokens:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=70.0.0
    - pyyaml
    - click
    - pip
  run:
    - python >=3.8
    - pyyaml
    - chardet
    - click

test:
  imports:
    - mathics_scanner
  commands:
    - pip check
    - mathics3-generate-json-table --help
    - mathics3-generate-operator-json-table --help
    - mathics3-tokens --help
  requires:
    - pip

about:
  home: https://pypi.org/project/Mathics-Scanner/
  summary: Character Tables and Tokenizer for Mathics and the Wolfram Language.
  dev_url: https://github.com/Mathics3/mathics-scanner
  license: Apache-2.0
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - mmatera
